#AdminApp.install('/work/app/was-kerberos-database.war', '[ -nopreCompileJSPs -distributeApp -nouseMetaDataFromBinary -appname was-kerberos-database_war -createMBeansForResources -noreloadEnabled -nodeployws -validateinstall warn -noprocessEmbeddedConfig -filepermission .*\.dll=755#.*\.so=755#.*\.a=755#.*\.sl=755 -noallowDispatchRemoteInclude -noallowServiceRemoteInclude -asyncRequestDispatchType DISABLED -nouseAutoLink -noenableClientModule -clientMode isolated -novalidateSchema -contextroot /was-kerberos-database -MapResRefToEJB [[ was-kerberos-database.war "" was-kerberos-database.war,WEB-INF/web.xml jdbc/krb5ds javax.sql.DataSource jdbc/krb5ds "" "" "" ]] -MapModulesToServers [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml WebSphere:cell=DefaultCell01,node=DefaultNode01,server=server1 ]] -MapWebModToVH [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml default_host ]] -CtxRootForWebMod [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml /was-kerberos-database ]]]' ) 
#9.0
AdminApp.install('/work/app/was-kerberos-database.war', '[ -nopreCompileJSPs -distributeApp -nouseMetaDataFromBinary -appname was-kerberos-database_war -createMBeansForResources -noreloadEnabled -nodeployws -validateinstall warn -noprocessEmbeddedConfig -filepermission .*\.dll=755#.*\.so=755#.*\.a=755#.*\.sl=755 -noallowDispatchRemoteInclude -noallowServiceRemoteInclude -asyncRequestDispatchType DISABLED -nouseAutoLink -noenableClientModule -clientMode isolated -novalidateSchema -contextroot /was-kerberos-database -MapResRefToEJB [[ was-kerberos-database.war "" was-kerberos-database.war,WEB-INF/web.xml jdbc/nokrb5 javax.sql.DataSource jdbc/nokrb5 "" "" "" ][ was-kerberos-database.war "" was-kerberos-database.war,WEB-INF/web.xml jdbc/krb5ds javax.sql.DataSource jdbc/krb5ds KerberosMapping "" "" ]] -MapModulesToServers [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml WebSphere:cell=DefaultCell01,node=DefaultNode01,server=server1 ]] -MapWebModToVH [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml default_host ]] -CtxRootForWebMod [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml /was-kerberos-database ]]]' ) 
#8.5.5
#AdminApp.install('/work/app/was-kerberos-database.war', '[ -nopreCompileJSPs -distributeApp -nouseMetaDataFromBinary -nodeployejb -appname was-kerberos-database_war -createMBeansForResources -noreloadEnabled -nodeployws -validateinstall warn -noprocessEmbeddedConfig -filepermission .*\.dll=755#.*\.so=755#.*\.a=755#.*\.sl=755 -noallowDispatchRemoteInclude -noallowServiceRemoteInclude -asyncRequestDispatchType DISABLED -nouseAutoLink -noenableClientModule -clientMode isolated -novalidateSchema -contextroot /was-kerberos-database -MapResRefToEJB [[ was-kerberos-database.war "" was-kerberos-database.war,WEB-INF/web.xml jdbc/krb5ds javax.sql.DataSource jdbc/krb5ds "" "" "" ]] -MapModulesToServers [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml WebSphere:cell=DefaultCell01,node=DefaultNode01,server=server1 ]] -MapWebModToVH [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml default_host ]] -CtxRootForWebMod [[ was-kerberos-database.war was-kerberos-database.war,WEB-INF/web.xml /was-kerberos-database ]]]' )

#Update app for kerberos login
#AdminApp.edit('was-kerberos-database_war', '[ -MapResRefToEJB [[ was-kerberos-database.war "" was-kerberos-database.war,WEB-INF/web.xml jdbc/krb5ds javax.sql.DataSource jdbc/krb5ds KerberosMapping "" "" ]]]' ) 

#Map users
AdminTask.createUser('[-uid dbuser -cn db -sn user -password password -confirmPassword password]')
AdminApp.edit('was-kerberos-database_war', '[ -MapRolesToUsers [[ Manager AppDeploymentOption.No AppDeploymentOption.No dbuser "" AppDeploymentOption.No user:defaultWIMFileBasedRealm/uid=dbuser,o=defaultWIMFileBasedRealm "" ]]]' )

AdminConfig.save()